  export const countryCodeMap: Record<string, string> = {
    American: 'us',
    British: 'gb',
    Canadian: 'ca',
    Chinese: 'cn',
    Dutch: 'nl',
    Egyptian: 'eg',
    French: 'fr',
    Greek: 'gr',
    Indian: 'in',
    Irish: 'ie',
    Italian: 'it',
    Jamaican: 'jm',
    Japanese: 'jp',
    Kenyan: 'ke',
    Malaysian: 'my',
    Mexican: 'mx',
    Moroccan: 'ma',
    Polish: 'pl',
    Portuguese: 'pt',
    Russian: 'ru',
    Spanish: 'es',
    Thai: 'th',
    Tunisian: 'tn',
    Turkish: 'tr',
    Unknown: 'un',
    Vietnamese: 'vn',
  };